# Generated by Django 5.1.2 on 2024-11-26 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('created_at', models.DateTimeField(
                    db_index=True,
                    default=django.utils.timezone.now,
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    db_index=True,
                )),
                ('event_type', models.CharField(max_length=255)),
                ('event_data', models.JSONField()),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('processed', 'Processed'),
                        ('failed', 'Failed'),
                    ],
                    db_index=True,
                    default='pending',
                    max_length=20,
                )),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(
                    blank=True,
                    null=True,
                )),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['status', 'created_at'],
                        name='core_outbox_status_99ab3a_idx',
                    ),
                ],
            },
        ),
    ]
