# Generated by Django 5.1.2 on 2025-02-17 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.CharField(max_length=50)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.BigIntegerField(default=1)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'outbox_event',
            },
        ),
    ]
