# Generated by Django 5.1.2 on 2024-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(auto_now_add=True)),
                ('environment', models.CharField(max_length=100)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['event_date_time'], name='core_evento_event_d_f52ca2_idx')],
            },
        ),
    ]
