# Generated by Django 5.1.2 on 2024-12-01 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(choices=[('user_created', 'User Created')], max_length=50)),
                ('environment', models.CharField(max_length=50)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.BigIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='PENDING', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='log_manager_status_77c4a1_idx')],
            },
        ),
    ]
