name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Copy environment variables
        run: cp src/core/.env.ci src/core/.env

      - name: Build and start containers
        run: make run

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: make lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: make test

  teardown:
    needs: [migrations, lint, test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Tear down containers
        run: docker compose down
